p: ''
  '(      
    (rosewater . "${p.rosewater}")
    (flamingo . "${p.flamingo}")
    (pink . "${p.pink}")
    (mauve . "${p.mauve}")
    (red . "${p.red}")
    (maroon . "${p.maroon}")
    (peach . "${p.peach}")
    (yellow . "${p.yellow}")
    (green . "${p.green}")
    (teal . "${p.teal}")
    (sky . "${p.sky}")
    (sapphire . "${p.sapphire}")
    (blue . "${p.blue}")
    (lavender . "${p.lavender}")
    (text . "${p.text}")
    (subtext1 . "${p.subtext1}")
    (subtext0 . "${p.subtext0}")
    (overlay2 . "${p.overlay2}")
    (overlay1 . "${p.overlay1}")
    (overlay0 . "${p.overlay0}")
    (surface2 . "${p.surface2}")
    (surface1 . "${p.surface1}")
    (surface0 . "${p.surface0}")
    (base . "${p.base}")
    (mantle . "${p.mantle}")
    (crust . "${p.crust}")
  )
''
