# Joe's dotfiles
# Copyright (C) 2023  Josep Jesus Bigorra Algaba (jjbigorra@gmail.com)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

stages:
  - lint
      
check-nix-files-syntax:
  image: nixos/nix:master
  stage: lint
  script: |
    find . -name '*.nix' -print0 | xargs -r0 nix-instantiate --parse-only 
    nix-shell -p statix --run 'statix check'
    nix-shell -p deadnix --run 'deadnix -f'

compile-scss-files:
  image: nixos/nix:master
  stage: lint
  script: |
    cd nix/nixos/users/joe/ags
    
    echo '$backgroundColor: rgba(29,32,33,0.7);' >> css/ags-variables.scss
    echo '$backgroundColor2: rgba(29,32,33,0.7);' >> css/ags-variables.scss
    echo '$highlightColor: #d79921;' >> css/ags-variables.scss
    echo '$foregroundColor: #ebdbb2;' >> css/ags-variables.scss
    echo '$foregroundColor2: #ebdbb2;' >> css/ags-variables.scss
    echo '$wallpaperPath: url("/home/joe/Ontwikkeling/Persoonlijk/dotfiles/nix/wallpapers/emzka1wnfaga1.png");' >> css/ags-variables.scss

    nix-shell -p dart-sass --run 'sass --no-source-map css/style.scss css/style.css'
    cat css/style.css

