* Joe's Dotfiles Contributing Guide

** Welcome

Welcome to the Joe's Dotfiles Contributing Guide, and thank you for your interest in this project.

If you would like to contribute to a specific part of the project, check out the following list of contributions that we accept and their corresponding sections that are within this guide.

Feel free to *fork* this project and create a *merge request* once you feel your changes can be merged back to the *trunk* branch of the original repository.

** List of maintainers

- Josep Bigorra ( *jjbigorra@gmail.com* )

* Contributing new code and/or improvements to code

When contributing code, you should keep in mind:
- Try to write code that is flexible, without hardcoded values when possible, so as to allow this code to cater to many.
- Try to create merge requests that are small and with a single purpose, when possible. This makes reviewing much easier.

This project welcomes and thrives on your contributions, to bring it further and to constantly improve it.


* Contributing documentation and/or improvements to documentation

When contributing documentation, you should keep in mind:
- Try to document things for a "general audience", with simple language when possible, and with accompanying resources that may help ellucidate documentation.
- Try to be thorough, consistent, and document things "fully" and explicitly, even seemingly obvious things. This helps newcomers get up to speed much faster.

This project welcomes and thrives on your contributions, to bring it further and to constantly improve it.

* Contributing ideas

To share your new ideas for the project, perform the following actions:

- Either create a GitLab issue in the project, and proceed to explain your idea as well as possible, with accompanying resources and images
- Or alternatively, email to <jjbigorra@gmail.com> describing your idea as well as possible If Joe decides to adopt it, Joe will ensure that an "issue" gets created in GitLab, so as to track and prioritize the idea. Otherwise you are free to implement and propose code to be merged.

* Joe's Dotfiles overview

See the [[file:README.org][README.org]] for more information.

* Ground rules - Code of Conduct

Before contributing, read our Code of Conduct to learn more about our community guidelines and expectations.

In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

** Our Standards

Examples of behavior that contributes to creating a positive environment include:

*** Using welcoming and inclusive language
*** Being respectful of differing viewpoints and experiences
*** Gracefully accepting constructive criticism
*** Focusing on what is best for the community
*** Showing empathy towards other community members

Examples of unacceptable behavior by participants include:

*** The use of sexualized language or imagery and unwelcome sexual attention or  advances
*** Trolling, insulting/derogatory comments, and personal or political attacks
*** Public or private harassment
*** Publishing others' private information, such as a physical or electronic  address, without explicit permission
*** Other conduct which could reasonably be considered inappropriate in a  professional setting

** Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

**  Scope

This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.

Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event.

Representation of a project may be further defined and clarified by project maintainers.

** Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting any of the maintainers.

All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances.

The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.
